package com.pos.sdkdemo.trade.Dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pos.sdkdemo.trade.bean.BillBean;
import com.pos.sdkdemo.trade.bean.TransactionData;

import com.pos.sdkdemo.trade.Dao.BillBeanDao;
import com.pos.sdkdemo.trade.Dao.TransactionDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig billBeanDaoConfig;
    private final DaoConfig transactionDataDaoConfig;

    private final BillBeanDao billBeanDao;
    private final TransactionDataDao transactionDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        billBeanDaoConfig = daoConfigMap.get(BillBeanDao.class).clone();
        billBeanDaoConfig.initIdentityScope(type);

        transactionDataDaoConfig = daoConfigMap.get(TransactionDataDao.class).clone();
        transactionDataDaoConfig.initIdentityScope(type);

        billBeanDao = new BillBeanDao(billBeanDaoConfig, this);
        transactionDataDao = new TransactionDataDao(transactionDataDaoConfig, this);

        registerDao(BillBean.class, billBeanDao);
        registerDao(TransactionData.class, transactionDataDao);
    }
    
    public void clear() {
        billBeanDaoConfig.clearIdentityScope();
        transactionDataDaoConfig.clearIdentityScope();
    }

    public BillBeanDao getBillBeanDao() {
        return billBeanDao;
    }

    public TransactionDataDao getTransactionDataDao() {
        return transactionDataDao;
    }

}
